### ISSUE TITLE
FW: E-FATURA GÖNDERİM HATASI 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#175]
Saygılarımla.

Kemal Hatunoğlu

Yazılım Uzmanı

Software Specialist

IES YAZILIM VE DANIŞMANLIK SAN. TİC.LTD.ŞTİ.

Gürsel Mahallesi Nurtaç Cad. No:9/5

KAĞITHANE / İSTANBUL

kemal.hatunoglu@iesyazilim.com.tr

 

 

 

Tel

:

+90 212 416 79 65

Cep

:

+90 544 202 01 14

Web:

:

 <http://www.iesyazilim.com.tr/> www.iesyazilim.com.tr

 

 

From: Tuğba <tugba@nazarmobilya.com> 
Sent: Thursday, May 20, 2021 1:37 PM
To: logodestek@iesyazilim.com.tr; yazilimdestek@iesyazilim.com.tr
Cc: 'Fatma AKDAĞ' <fatma@nazarmobilya.com>
Subject: E-FATURA GÖNDERİM HATASI

 

E fatura gönderdiğim bir müşteride GB etiketinden dolayı hata alıyorum güncellemek istediğimde GB etiketi boş gözüküyor kopyalama vs yapamıyorum bununla alakalı sizin yapabileceğiniz bir şey varmı acaba?

 

 

 

    

      Tuğba DÜZEY YALÇINKAYA

            Muhasebe

         0212 494 58 58

 

[File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/570c794b-2f8f-438a-910c-38535bffbc50.jpg)

[File 2](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/f0c6fdd0-f93c-4d11-98f9-2a4e3a7392f6.jpg)
<kemal.hatunoglu@iesyazilim.com.tr> adresinden, 27.05.21 de saat: 10.28 gönderim yapmıştır.

**Comment by burakergun394** [comment]
MERHABA sorun destek ekibine iletildi.
