### ISSUE TITLE
Kemalden Bir mail daha 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#176]
Selamlar 

 

Saygılarımla.

Kemal Hatunoğlu

Yazılım Uzmanı

Software Specialist

IES YAZILIM VE DANIŞMANLIK SAN. TİC.LTD.ŞTİ.

Gürsel Mahallesi Nurtaç Cad. No:9/5

KAĞITHANE / İSTANBUL

kemal.hatunoglu@iesyazilim.com.tr

 

 

 

Tel

:

+90 212 416 79 65

Cep

:

+90 544 202 01 14

Web:

:

 <http://www.iesyazilim.com.tr/> www.iesyazilim.com.tr

 

 

[File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/34d49ab1-8034-49a3-82af-e1630b38ab8b.jpg)
<kemal.hatunoglu@iesyazilim.com.tr> adresinden, 27.05.21 de saat: 10.36 gönderim yapmıştır.

**Comment by burakergun394** [comment]
Yoru m1

**Comment by burakergun394** [comment]
Yorum 2

**Comment by burakergun394** [comment]
Yorum 3
