### ISSUE TITLE
Kemal'den 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#177]
![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/b5923ce7-1325-4565-9b43-25e12deb8746.jpg)
"kemalhatunoglu@gmail.com" <kemalhatunoglu@gmail.com> adresinden, 27.05.21 de saat: 10.43 gönderim yapmıştır.

**Comment by burakergun394** [comment]
SIRMA GÜZEL REKLAM VERMİS
![Untitled (16)](https://user-images.githubusercontent.com/47159921/119786110-834ce480-bed8-11eb-9fc8-b8358b9949d5.jpeg)

**Comment by burakergun394** [comment]
aada
