### ISSUE TITLE
WESDFGHJKLŞİ, 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#178]
Q            AESRDTFYGUHIJOKPLĞŞİ,

WSERDTFYHUJIKOPLĞŞÜİ

,

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/73ccf329-4efd-493f-ab16-9d15e934450d.jpg)
<burak.ergun@iesyazilim.com.tr> adresinden, 27.05.21 de saat: 10.48 gönderim yapmıştır.

**Comment by burakergun394** [comment]
BU NEDİR KARDES
