### ISSUE TITLE
Merhaba Test 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#179]
Test maili

<burak.ergun@iesyazilim.com.tr> adresinden, 27.05.21 de saat: 12.20 gönderim yapmıştır.

**Comment by burakergun394** [comment]
İssue kapandı
![Untitled (17)](https://user-images.githubusercontent.com/47159921/119801354-4c7dcb00-bee6-11eb-91b5-8c720bdb9d32.jpeg)
