### ISSUE TITLE
FW: Deneme Kemal 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#191]
Saygılarımla.
Kemal Hatunoğlu
Yazılım Uzmanı
Software Specialist
IES YAZILIM VE DANIŞMANLIK SAN. TİC.LTD.ŞTİ.
Gürsel Mahallesi Nurtaç Cad. No:9/5
KAĞITHANE / İSTANBUL
kemal.hatunoglu@iesyazilim.com.tr
 
 
 
Tel
:
+90 212 416 79 65
Cep
:
+90 544 202 01 14
Web:
:
www.iesyazilim.com.tr

-----Original Message-----
From: iesyazilim@hotmail.com <iesyazilim@hotmail.com> 
Sent: Friday, May 28, 2021 11:03 AM
To: kemal.hatunoglu@iesyazilim.com.tr
Subject: Re: Deneme Kemal

Bu bir test mesajıdır ve ekte bir resim belirtilmiştir.
!bkz [RecyclerCommentLa-2]

28 Mayıs 2021 Cuma 11:00 tarihinde, kemal.hatunoglu@iesyazilim.com.tr yazdi:
> Ş ı İ ü ğ J j dolu hayatımız 😊
> 
> 
> 
> Saygılarımla.
> 
> 
> Kemal Hatunoğlu
> 
> Yazılım Uzmanı
> 
> Software Specialist
> 
> IES YAZILIM VE DANIŞMANLIK SAN. TİC.LTD.ŞTİ.
> 
> Gürsel Mahallesi Nurtaç Cad. No:9/5
> 
> KAĞITHANE / İSTANBUL
> 
> 
> kemal.hatunoglu@iesyazilim.com.tr
> 
> 
>  
> 
>  
> 
>  
> 
> 
> Tel
> 
> :
> 
> +90 212 416 79 65
> 
> 
> Cep
> 
> :
> 
> +90 544 202 01 14
> 
> 
> Web:
> 
> :
> 
>  <http://www.iesyazilim.com.tr/> www.iesyazilim.com.tr
> 
>  
> 
> 
> 
>  
> 

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/a65bf725-2661-4d2e-99a0-572ff52f8b62.jpeg)
<kemal.hatunoglu@iesyazilim.com.tr>(137) adresinden, 28.05.21 de saat: 11.05 gönderim yapmıştır.

**Comment by burakergun394** [comment]
tekrardan reply edildi kemal ----
