### ISSUE TITLE
Kemal Denemelere doymuyordu. 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#192]
Selamlar Burak Ergün Tanıştığıma çok memnun oldum. 😊

Saygılarımla.

Kemal Hatunoğlu

Yazılım Uzmanı

Software Specialist

IES YAZILIM VE DANIŞMANLIK SAN. TİC.LTD.ŞTİ.

Gürsel Mahallesi Nurtaç Cad. No:9/5

KAĞITHANE / İSTANBUL

kemal.hatunoglu@iesyazilim.com.tr

 

 

 

Tel

:

+90 212 416 79 65

Cep

:

+90 544 202 01 14

Web:

:

 <http://www.iesyazilim.com.tr/> www.iesyazilim.com.tr

 

 

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/1cbd64f0-d6cd-4f19-a114-659c358a7c4b.png)

![File 2](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/72596b44-c62f-4b09-b373-5c06b465740c.jpg)

![File 3](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/a32b72d4-4bdc-443c-baba-de1f0e94dce8.jpg)
<kemal.hatunoglu@iesyazilim.com.tr>(140) adresinden, 28.05.21 de saat: 11.14 gönderim yapmıştır.

**Comment by burakergun394** [comment]
Burak denemelere doymuyordu.
[article-black-android.zip](https://github.com/Kemalhatunoglu/GithubIntegrationTest/files/6559332/article-black-android.zip)

**Comment by burakergun394** [comment]
Tekrardan gönderildi.
[Uploading logout-black-android.zip…]()

**Comment by burakergun394** [comment]
Tekrardan gönderildi.
[assignment_ind-black-android.zip](https://github.com/Kemalhatunoglu/GithubIntegrationTest/files/6559377/assignment_ind-black-android.zip)
