### ISSUE TITLE
Sample issue 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#196]
I have problem with some nuget packages please help me 

 

 

 

Saygılarımla,

 

Ahmet Faruk ULU

Yazılım Geliştirme Uzmanı

  _____  

Tel           : 0(212) 416 79 65

Gsm        : 0(531) 034 32 11

Web        :  <http://www.iesyazilim.com.tr> www.iesyazilim.com.tr

Lütfen gerekli olmadıkça bu dökümanın kağıt çıktısını almayın, doğamızı
koruyun.

  _____  

Bu elektronik posta mesajı ve ekleri sadece gönderildiği kişi veya kuruma
özeldir ve gizli bilgiler içerebilir. Eğer bu mesajı hataen aldıysanız
lütfen bu durumu gönderen kişiye derhal bildiriniz ve mesajı sisteminizden
siliniz. Eğer doğru kişiye ulaşmadığını düşünüyorsanız, bu mesajın
gizlenmesi, yönlendirilmesi, kopyalanması veya herhangi bir şekilde
kullanılması yasaktır. Internet iletişiminde güvenlik ve hatasız gönderim
garanti edilemeyeceğinden, mesajın yerine ulaşmaması, geç ulaşması,
içeriğinin bozulması ya da mesajın virüs taşıması gibi problemler
oluşabilir. Gönderen taraf bu tip sorunlardan sorumlu tutulmaz.

This message and attachments are confidential and intended solely for the
individual(s) stated in this message. If you received this message although
you are not the addressee, you are responsible to keep the message
confidential. The sender has no responsibility for the accuracy or
correctness of the information in the message and its attachments. Our
company shall have no liability for any changes or late receiving, loss of
integrity and confidentiality, viruses and any damages caused in anyway to
your computer system.

 

 

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/0908c0c1-788f-4b89-9e76-c3ab56a5e689.png)
"Ahmet Faruk ULU" <ahmetfaruk.ulu@iesyazilim.com.tr>(149) adresinden, 28.05.21 de saat: 17.02 gönderim yapmıştır.

**Comment by burakergun394** [comment]
What can I do Sometimes
[article-black-android.zip](https://github.com/Kemalhatunoglu/GithubIntegrationTest/files/6561330/article-black-android.zip)

**Comment by burakergun394** [comment]
ABACAS
[Uploading share_location-black-android.zip…]()
