### ISSUE TITLE
Sample issue 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#197]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-9"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style></style></head><body lang="TR" link="#0563C1" vlink="#954F72"><div class="WordSection1"><p class="MsoNormal">I have problem with some nuget packages please help me <o:p></o:p></p><p class="MsoNormal"><o:p>&nbsp;</o:p></p><p class="MsoNormal"><span style="mso-fareast-language:TR"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-fareast-language:TR"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,sans-serif;color:#1F497D;mso-fareast-language:TR">Saygılarımla,<o:p></o:p></span></p><p class="MsoNormal" style="line-height:13.5pt"><span style="font-size:10.0pt;color:black;mso-fareast-language:TR"><o:p>&nbsp;</o:p></span></p><table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0" style="border-collapse:collapse"><tr><td width="198" valign="top" style="width:148.85pt;padding:0cm 5.4pt 0cm 5.4pt"><p class="MsoNormal" style="mso-line-height-alt:13.5pt"><b><span style="font-size:14.0pt;color:#2F3542;mso-fareast-language:TR">Ahmet Faruk ULU<o:p></o:p></span></b></p><p class="MsoNormal" style="line-height:13.5pt"><span style="color:#595959;mso-fareast-language:TR">Yazılım Geliştirme Uzmanı</span><span style="font-size:5.0pt;color:#595959;mso-fareast-language:TR"><o:p></o:p></span></p><div><div class="MsoNormal"><b><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR"><hr size="1" width="93%" noshade="" style="color:#BFBFBF" align="left"></span></b></div></div><p class="MsoNormal"><b><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR">Tel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :</span></b><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR"> 0(212) 416 79 65</span><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR"><o:p></o:p></span></p><p class="MsoNormal"><b><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR">Gsm&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :</span></b><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR"> 0(531) 034 32 11<o:p></o:p></span></p><p class="MsoNormal"><b><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR">Web&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :</span></b><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR"> </span><span style="mso-fareast-language:TR"><a href="http://www.iesyazilim.com.tr"><span style="font-size:9.0pt;color:#0563C1">www.iesyazilim.com.tr</span></a></span><span style="font-size:9.0pt;color:#A6A6A6;mso-fareast-language:TR"><o:p></o:p></span></p></td><td width="428" valign="top" style="width:320.95pt;padding:0cm 5.4pt 0cm 5.4pt"><p class="MsoNormal" style="line-height:13.5pt"><span style="font-size:10.0pt;color:#1F497D;mso-fareast-language:TR"><img border="0" width="208" height="84" id="Resim_x0020_1" src="cid:image001.png@01D753E3.4AE59340"><o:p></o:p></span></p></td></tr><tr><td width="626" colspan="2" valign="top" style="width:469.8pt;padding:0cm 5.4pt 0cm 5.4pt"><p class="MsoNormal" style="line-height:13.5pt"><b><span style="font-size:9.0pt;color:#00622C;mso-fareast-language:TR">Lütfen gerekli olmadıkça bu dökümanın kağıt çıktısını almayın, doğamızı koruyun.</span></b><span style="font-size:10.0pt;color:#1F497D;mso-fareast-language:TR"><o:p></o:p></span></p></td></tr></table><div class="MsoNormal" align="center" style="text-align:center"><b><span style="font-size:9.0pt;color:#989FAF;mso-fareast-language:TR"><hr size="2" width="100%" align="center"></span></b></div><p class="MsoNormal" style="margin-bottom:12.0pt"><span style="font-size:7.5pt;font-family:&quot;Arial&quot;,sans-serif;color:gray;mso-fareast-language:TR">Bu elektronik posta mesajı ve ekleri sadece gönderildiği kişi veya kuruma özeldir ve gizli bilgiler içerebilir. Eğer bu mesajı hataen aldıysanız lütfen bu durumu gönderen kişiye derhal bildiriniz ve mesajı sisteminizden siliniz. Eğer doğru kişiye ulaşmadığını düşünüyorsanız, bu mesajın gizlenmesi, yönlendirilmesi, kopyalanması veya herhangi bir şekilde kullanılması yasaktır. Internet iletişiminde güvenlik ve hatasız gönderim garanti edilemeyeceğinden, mesajın yerine ulaşmaması, geç ulaşması, içeriğinin bozulması ya da mesajın virüs taşıması gibi problemler oluşabilir. Gönderen taraf bu tip sorunlardan sorumlu tutulmaz.</span><span style="font-size:7.5pt;font-family:&quot;Arial&quot;,sans-serif;color:gray;mso-fareast-language:TR"><o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:7.5pt;font-family:&quot;Arial&quot;,sans-serif;color:gray;mso-fareast-language:TR">This message and attachments are confidential and intended solely for the individual(s) stated in this message. If you received this message although you are not the addressee, you are responsible to keep the message confidential. The sender has no responsibility for the accuracy or correctness of the information in the message and its attachments. Our company shall have no liability for any changes or late receiving, loss of integrity and confidentiality, viruses and any damages caused in anyway to your computer system.</span><span style="color:#1F497D;mso-fareast-language:TR"><o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,sans-serif;color:#1F497D;mso-fareast-language:TR"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><o:p>&nbsp;</o:p></p></div></body></html>
![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/9bebb436-e254-4d83-ab2c-a5e113af01e9.png)
"Ahmet Faruk ULU" <ahmetfaruk.ulu@iesyazilim.com.tr>(149) adresinden, 28.05.21 de saat: 17.02 gönderim yapmıştır.

**Comment by burakergun394** [comment]
TEST WİTH OLD MESSAGE REPLY, PLEASE COME TO DC ROOM
[message-black-android.zip](https://github.com/Kemalhatunoglu/GithubIntegrationTest/files/6568335/message-black-android.zip)
