### ISSUE TITLE
tamamdır 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#203]
Selamlar.

 

 

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/2100811d-b293-457d-a992-be90804eca80.jpg)

![File 2](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/b7f7ae29-7d1a-4dd4-9bea-676c600ed452.png)

![File 3](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/29026f31-22f4-4400-be83-f7a0e1bb30e7.png)
<kemal.hatunoglu@iesyazilim.com.tr>(169) adresinden, 31.05.21 de saat: 10.40 gönderim yapmıştır.

**Comment by burakergun394** [comment]
[message-black-android.zip](https://github.com/Kemalhatunoglu/GithubIntegrationTest/files/6568613/message-black-android.zip)
a1a1a1

**Comment by burakergun394** [comment]
a1a
[message-black-android.zip](https://github.com/Kemalhatunoglu/GithubIntegrationTest/files/6568652/message-black-android.zip)

**Comment by burakergun394** [comment]
merhaba

**Comment by burakergun394** [comment]
merhaba
