### ISSUE TITLE
gmail tarayıcıdan atılan mesaj 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#205]
Selamlar

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/3688820c-599d-4262-b57b-961ec18293b2.png)
"Kemal Hatunoglu" <kemalhatunoglu@gmail.com>(172) adresinden, 31.05.21 de saat: 10.49 gönderim yapmıştır.

**Comment by burakergun394** [comment]
AB1
[message-black-android.zip](https://github.com/Kemalhatunoglu/GithubIntegrationTest/files/6568667/message-black-android.zip)

**Comment by burakergun394** [comment]
A1AA1
