### ISSUE TITLE
Gömülü 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#206]
[image: Ufak.png]

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/8cea226e-e249-4c7b-b871-89baf27748b8.png)
"Kemal Hatunoglu" <kemalhatunoglu@gmail.com>(174) adresinden, 31.05.21 de saat: 10.58 gönderim yapmıştır.

**Comment by burakergun394** [comment]
a1a1

**Comment by Kemalhatunoglu** [comment]
gelirm

**Comment by Kemalhatunoglu** [comment]
kapan artık

**Comment by burakergun394** [comment]
A1

**Comment by burakergun394** [comment]
A

**Comment by burakergun394** [comment]
a

**Comment by burakergun394** [comment]
A
