### ISSUE TITLE
RE: test 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#219]
Sorun cözelemedi

 

From: iesyazilim@hotmail.com <iesyazilim@hotmail.com> 
Sent: Tuesday, June 1, 2021 11:09 AM
To: burak.ergun@iesyazilim.com.tr
Subject: Re: test

 

a

  _____  

1 Haziran 2021 Salı 10:17 tarihinde, burak.ergun@iesyazilim.com.tr <mailto:burak.ergun@iesyazilim.com.tr>  adresinden gelen maile cevap olarak yollanmıştır. 

12           a

 

 

![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/5149a1c9-bf23-4552-8763-d0bffe23ec39.jpg)

![File 2](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/b95f9610-da95-4423-a60c-ab04d3f44046.jpg)
<burak.ergun@iesyazilim.com.tr>(197) adresinden, 01.06.21 de saat: 11.14 gönderim yapmıştır.

**Comment by burakergun394** [comment]
![7670cc33-5ea6-4985-94c7-1cc0999477a2](https://user-images.githubusercontent.com/47159921/120291007-8b879400-c2cb-11eb-9f08-f1dad2837ea1.jpg)
pijamalı hasta yağız çöpü tuttu iç

**Comment by burakergun394** [comment]
aa

**Comment by burakergun394** [comment]
a
