### ISSUE TITLE
Gmail'den Gömülü 

### ISSUE THREAD

**Issue by Kemalhatunoglu** [Kemalhatunoglu/GithubIntegrationTest#221]
![File 1](https://raw.githubusercontent.com/Kemalhatunoglu/GithubIntegrationImages/main/images/6e595261-f800-4767-b11c-a5066eca3144.png)
<kemalhatunoglu@gmail.com>(203) adresinden, 02.06.21 de saat: 11.00 gönderim yapmıştır.

**Comment by burakergun394** [comment]
test 
![7670cc33-5ea6-4985-94c7-1cc0999477a2](https://user-images.githubusercontent.com/47159921/120446222-031ff680-c392-11eb-8a99-3f320ee18880.jpg)
